//jshint esversion:6

module.exports = [
    '',
    '<span id="Co. Offaly">Co. Uíbh Fhailí</span>',
    '<span id="">Co. Lú</span>',
    '<span id="">Co. Loch Garman</span>',
    '<span id="">Co. Luimnigh</span>',
    '<span id="">Co. Átha Chliath</span>',
    '<span id="">Co. Liatroma</span>',
    '<span id="">Co. Aontroma</span>',
    '<span id="">Co. Dhún na nGall</span>',
    '<span id="">Co. Fhear Manach</span>',
    '<span id="">Co. Chorcaí</span>',
    '<span id="">Co. Chill Mhantáin</span>',
    '<span id="">Co. Ros Comáin</span>',
    '<span id="">Co. Dhoire</span>',
    '<span id="">Co. Shligigh</span>',
    '<span id="">Co. Thiobraid Árann</span>',
    '<span id="">Co. Laoise</span>',
    '<span id="">Co. Phort Láirge</span>',
    '<span id="">Co. Chill Chainnigh</span>',
    '<span id="">Co. Na Mí</span>',
    '<span id="">Co. Chiarraí</span>',
    '<span id="">Co. An Longfoirt</span>',
    '<span id="">Co. Mhaigh Eo</span>',
    '<span id="">Co. Na hIarmhí</span>',
    '<span id="">Co. An Dúin</span>',
    '<span id="">Co. Ard Mhacha</span>',
    '<span id="">Co. Cheatharlach</span>',
    '<span id="">Co. Mhuineacháin</span>',
    '<span id="">Co. na Gaillimhe</span>',
    '<span id="">Co. Chill Dara</span>',
    '<span id="">Co. An Chláir</span>',
    '<span id="Co. Cavan">Co. An Cabháin</span>',
    '<span id="Co. Tyrone">Co. Thír Eoghain</span>',
    '<span id="A land beyond the sea">Tír Thar Muir</span>',
    '<span id="The language">An Teanga</span>'
];
